const NAMES = {
    bosses: "Bosses",
    weapons: "Weapons",
    armors: "Armors",
    gestures: "Gestures",
    rings: "Rings",
    pendants: "Pendants",
    umbralEyes: "Umbral Eyes",
    achievements: "Achievements",
    spells: "Spells",
};

const SUBCATEGORIES_NAMES = {
    axes_and_hammers: "Axes",
    bows: "Bows",
    catalysts: "Catalysts",
    crossbow: "Crossbows",
    daggers: "Daggers",
    fists: "Fists",
    flails: "Flails",
    grand_axes: "Grand Axes",
    grand_hammers: "Grand Hammers",
    grand_swords: "Grand Swords",
    hammers: "Hammers",
    long_swords: "Long Swords",
    polearms: "Polearms",
    short_swords: "Short Swords",
    spears: "Spears",
    ammunitions: "Ammunitions",
    helmets: "Helmets",
    chestplates: "Chestplates",
    gauntlets: "Gauntlets",
    legs: "Legs",
    umbral: "Umbral Spells",
    radiant: "Radiant Spells",
    inferno: "Inferno Spells",
    shields: "Shields",
};

export { NAMES, SUBCATEGORIES_NAMES };
