const NAMES = {
    bosses: "Bosses",
    weapons: "Weapons",
    armors: "Armors",
    gestures: "Gestures",
    rings: "Rings",
    pendants: "Pendants",
    umbralEyes: "Umbral Eyes",
    achievements: "Achievements",
    spells: "Spells",
};

const SUBCATEGORIES_NAMES = {
    axes: "Axes",
    bows: "Bows",
    catalysts: "Catalysts",
    crossbows: "Crossbows",
    daggers: "Daggers",
    fists: "Fists",
    flails: "Flails",
    "grand-axes": "Grand Axes",
    "grand-hammers": "Grand Hammers",
    "grand-swords": "Grand Swords",
    hammers: "Hammers",
    "long-swords": "Long Swords",
    polearms: "Polearms",
    "short-swords": "Short Swords",
    spears: "Spears",
    ammunitions: "Ammunitions",
    helmets: "Helmets",
    chestplates: "Chestplates",
    gauntlets: "Gauntlets",
    legs: "Legs",
    umbral: "Umbral Spells",
    radiant: "Radiant Spells",
    inferno: "Inferno Spells",
    shields: "Shields",
};

export { NAMES, SUBCATEGORIES_NAMES };
